os:
  - linux
  - osx

language: go
dist: trusty

go:
  - 1.8

git:
  depth: 10

env:
  global:
    - APM_TEST_PACKAGES="environment go-plus"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

script:
  - go get -u github.com/nsf/gocode
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
